package provider

import (
	"context"
	"crypto/rand"
	"fmt"
	"math/big"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	kuma "github.com/breml/go-uptime-kuma-client"
	"github.com/breml/go-uptime-kuma-client/monitor"
)

// pushTokenLength is the length of the push token generated by the
// Uptime Kuma browser frontend.  The server does not generate tokens
// itself, so the client must supply one.
const pushTokenLength = 32

// pushTokenChars is the set of characters used by the Uptime Kuma
// browser frontend when generating push tokens (see genSecret in
// src/util.ts).
const pushTokenChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

// generatePushToken generates a cryptographically secure random push
// token that mirrors the behaviour of the Uptime Kuma browser frontend.
func generatePushToken() (string, error) {
	charsLen := big.NewInt(int64(len(pushTokenChars)))
	token := make([]byte, pushTokenLength)

	for i := range token {
		idx, err := rand.Int(rand.Reader, charsLen)
		if err != nil {
			return "", fmt.Errorf("generate push token: %w", err)
		}

		token[i] = pushTokenChars[idx.Int64()]
	}

	return string(token), nil
}

var (
	_ resource.Resource                = &MonitorPushResource{}
	_ resource.ResourceWithImportState = &MonitorPushResource{}
)

// NewMonitorPushResource returns a new instance of the Push monitor resource.
func NewMonitorPushResource() resource.Resource {
	return &MonitorPushResource{}
}

// MonitorPushResource defines the resource implementation.
type MonitorPushResource struct {
	client *kuma.Client
}

// MonitorPushResourceModel describes the resource data model.
type MonitorPushResourceModel struct {
	MonitorBaseModel

	PushToken types.String `tfsdk:"push_token"`
}

// Metadata returns the metadata for the resource.
func (*MonitorPushResource) Metadata(
	_ context.Context,
	req resource.MetadataRequest,
	resp *resource.MetadataResponse,
) {
	resp.TypeName = req.ProviderTypeName + "_monitor_push"
}

// Schema returns the schema for the resource.
func (*MonitorPushResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Push monitor resource",
		Attributes: withMonitorBaseAttributes(map[string]schema.Attribute{
			"push_token": schema.StringAttribute{
				MarkdownDescription: "Unique push token generated during resource creation. Used to construct the push URL: `{baseURL}/api/push/{pushToken}?status=up&msg=OK&ping=`.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		}),
	}
}

// Configure configures the Push monitor resource with the API client.
func (r *MonitorPushResource) Configure(
	_ context.Context,
	req resource.ConfigureRequest,
	resp *resource.ConfigureResponse,
) {
	r.client = configureClient(req.ProviderData, &resp.Diagnostics)
}

// Create creates a new Push monitor resource.
func (r *MonitorPushResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data MonitorPushResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// The Uptime Kuma server does not generate push tokens — the browser
	// frontend generates them before sending the create request.  We
	// mirror that behaviour here so the monitor is created with a usable
	// push URL.
	pushToken, err := generatePushToken()
	if err != nil {
		resp.Diagnostics.AddError("failed to generate push token", err.Error())
		return
	}

	pushMonitor := monitor.Push{
		Base: monitor.Base{
			Name:           data.Name.ValueString(),
			Interval:       data.Interval.ValueInt64(),
			RetryInterval:  data.RetryInterval.ValueInt64(),
			ResendInterval: data.ResendInterval.ValueInt64(),
			MaxRetries:     data.MaxRetries.ValueInt64(),
			UpsideDown:     data.UpsideDown.ValueBool(),
			IsActive:       data.Active.ValueBool(),
		},
		PushDetails: monitor.PushDetails{
			PushToken: pushToken,
		},
	}

	if !data.Description.IsNull() {
		desc := data.Description.ValueString()
		pushMonitor.Description = &desc
	}

	if !data.Parent.IsNull() {
		parent := data.Parent.ValueInt64()
		pushMonitor.Parent = &parent
	}

	if !data.NotificationIDs.IsNull() {
		var notificationIDs []int64
		resp.Diagnostics.Append(data.NotificationIDs.ElementsAs(ctx, &notificationIDs, false)...)
		if resp.Diagnostics.HasError() {
			return
		}

		pushMonitor.NotificationIDs = notificationIDs
	}

	id, err := r.client.CreateMonitor(ctx, &pushMonitor)
	// Handle error.
	if err != nil {
		resp.Diagnostics.AddError("failed to create Push monitor", err.Error())
		return
	}

	data.ID = types.Int64Value(id)

	handleMonitorTagsCreate(ctx, r.client, id, data.Tags, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	err = handleMonitorActiveStateCreate(ctx, r.client, id, data.Active)
	if err != nil {
		resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
		resp.Diagnostics.AddError("failed to apply monitor active state", err.Error())
		return
	}

	var createdMonitor monitor.Push
	err = r.client.GetMonitorAs(ctx, id, &createdMonitor)
	// Handle error.
	if err != nil {
		resp.Diagnostics.AddError("failed to read created Push monitor", err.Error())
		return
	}

	data.PushToken = types.StringValue(createdMonitor.PushToken)

	// Populate state.
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Read reads the current state of the Push monitor resource.
func (r *MonitorPushResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data MonitorPushResourceModel

	// Get resource from state.
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	var pushMonitor monitor.Push
	err := r.client.GetMonitorAs(ctx, data.ID.ValueInt64(), &pushMonitor)
	// Handle error.
	if err != nil {
		if isNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("failed to read Push monitor", err.Error())
		return
	}

	data.Name = types.StringValue(pushMonitor.Name)
	if pushMonitor.Description != nil {
		data.Description = types.StringValue(*pushMonitor.Description)
	} else {
		data.Description = types.StringNull()
	}

	data.Interval = types.Int64Value(pushMonitor.Interval)
	data.RetryInterval = types.Int64Value(pushMonitor.RetryInterval)
	data.ResendInterval = types.Int64Value(pushMonitor.ResendInterval)
	data.MaxRetries = types.Int64Value(pushMonitor.MaxRetries)
	data.UpsideDown = types.BoolValue(pushMonitor.UpsideDown)
	data.Active = types.BoolValue(pushMonitor.IsActive)
	data.PushToken = types.StringValue(pushMonitor.PushToken)

	if pushMonitor.Parent != nil {
		data.Parent = types.Int64Value(*pushMonitor.Parent)
	} else {
		data.Parent = types.Int64Null()
	}

	if len(pushMonitor.NotificationIDs) > 0 {
		notificationIDs, diags := types.ListValueFrom(ctx, types.Int64Type, pushMonitor.NotificationIDs)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}

		data.NotificationIDs = notificationIDs
	} else {
		data.NotificationIDs = types.ListNull(types.Int64Type)
	}

	data.Tags = handleMonitorTagsRead(ctx, pushMonitor.Tags, data.Tags, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	// Populate state.
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Update updates the Push monitor resource.
func (r *MonitorPushResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data MonitorPushResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state MonitorPushResourceModel

	// Get resource from state.
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	pushMonitor := monitor.Push{
		Base: monitor.Base{
			ID:             data.ID.ValueInt64(),
			Name:           data.Name.ValueString(),
			Interval:       data.Interval.ValueInt64(),
			RetryInterval:  data.RetryInterval.ValueInt64(),
			ResendInterval: data.ResendInterval.ValueInt64(),
			MaxRetries:     data.MaxRetries.ValueInt64(),
			UpsideDown:     data.UpsideDown.ValueBool(),
			IsActive:       data.Active.ValueBool(),
		},
		PushDetails: monitor.PushDetails{
			PushToken: data.PushToken.ValueString(),
		},
	}

	if !data.Description.IsNull() {
		desc := data.Description.ValueString()
		pushMonitor.Description = &desc
	}

	if !data.Parent.IsNull() {
		parent := data.Parent.ValueInt64()
		pushMonitor.Parent = &parent
	}

	if !data.NotificationIDs.IsNull() {
		var notificationIDs []int64
		resp.Diagnostics.Append(data.NotificationIDs.ElementsAs(ctx, &notificationIDs, false)...)
		if resp.Diagnostics.HasError() {
			return
		}

		pushMonitor.NotificationIDs = notificationIDs
	}

	err := r.client.UpdateMonitor(ctx, &pushMonitor)
	// Handle error.
	if err != nil {
		resp.Diagnostics.AddError("failed to update Push monitor", err.Error())
		return
	}

	handleMonitorTagsUpdate(ctx, r.client, data.ID.ValueInt64(), state.Tags, data.Tags, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	handleMonitorActiveStateUpdate(ctx, r.client, data.ID.ValueInt64(), state.Active, data.Active, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	// Populate state.
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Delete deletes the Push monitor resource.
func (r *MonitorPushResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data MonitorPushResourceModel

	// Get resource from state.
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteMonitor(ctx, data.ID.ValueInt64())
	// Handle error.
	if err != nil {
		resp.Diagnostics.AddError("failed to delete Push monitor", err.Error())
		return
	}
}

// ImportState imports an existing resource by ID.
func (*MonitorPushResource) ImportState(
	ctx context.Context,
	req resource.ImportStateRequest,
	resp *resource.ImportStateResponse,
) {
	id, err := strconv.ParseInt(req.ID, 10, 64)
	// Handle error.
	if err != nil {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Import ID must be a valid integer, got: %s", req.ID),
		)
		return
	}

	// Populate state.
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
